### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by snehask7** [snehask7/Game-Website#1]
- [x] Add guest option

- [x] Forgot password functionality

- [x] New high score message

- [x] Animations on completion of game if new high score

- [ ] Complete atleast 1 other game

- [ ] Add friends option

- [ ] View leaderboard
